### PR TITLE
getUnchecked() implemented

### LINKED ISSUE #3: Don't throw a checked exception on get of try
Alex A says it should throw an unchecked exception on get.

### PR DESCRIPTION
**Pull request by pivovarit**
+ getUnchecked() implementation + readme update
+ and a little bit of cleanup

This one closes #3

### CODE REVIEW

**Comment by jasongoodwin** [comment]
Cool thanks. It says the branch has conflicts at the moment?
I don't think I've changed anything.
Thanks again

**Comment by pivovarit** [comment]
I am not sure why is this happening. I tried resolving this by merging it with master and everything was up to date.

**Comment by jasongoodwin** [comment]
Cool I'll check it out and let you know. I can hopefully look at this tomorrow.

**Comment by pivovarit** [comment]
@jasongoodwin now it's good to go :)

**Comment by jasongoodwin** [comment]
Thanks! Ill check it out tomorrow.

**Comment by jasongoodwin** [comment]
Sorry about the commits to master - I had done the same work you had done :)
I released 0.4.0

Thanks again!

**Pull request merged**
