### PR TITLE
New methods + refactor

### LINKED ISSUE #5: add onSuccess

### PR DESCRIPTION
**Pull request by pivovarit**
I extended Try class with onSuccess() method, which is an analogy to Java8's Optional's ifPresent() method. Also refactored a bit.

This closes #5

### CODE REVIEW

**Comment by jasongoodwin** [comment]
Hey sorry - I just saw this.
I'll try to merge it now.

**Comment by jasongoodwin** [comment]
K it's merged. I'll publish 0.1.0

**Comment by pivovarit** [comment]
Great :) btw, I pointed to this project during my presentation few days ago
http://www.slideshare.net/pivovarit/ja-48046212

**Comment by jasongoodwin** [comment]
Thanks!! This has been released as 0.1.0

**Pull request merged**
